name: davcalen
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0
  table_calendar: ^3.0.0
  intl: ^0.19.0
  sqflite_common_ffi: ^2.0.0
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_local_notifications: ^14.0.0+1
  fl_chart: ^0.63.0
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  shared_preferences: ^2.0.15
  animated_text_kit: ^4.2.1  # Añadimos solo esta línea para las animaciones de texto
  flutter_slidable: ^3.0.0  # Actualiza a la última versión
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  msix: ^3.16.8
msix_config:
  display_name: DAVCALEN
  publisher_display_name: DAVCALEN
  identity_name: com.davcalen.davcalen
  msix_version: 1.0.0.0

flutter:
  uses-material-design: true
